Models/Tablero.cs
using tl2_tp10_2023_julian_quin.ViewModels;

namespace tl2_tp10_2023_julian_quin;
public class Tablero 
{
    public int Id { get; set; }
    public int IdUsuarioPropietario { get; set; }
    public string NombrePropietario {get;set;} // simpre está en null, se completa solo en un traerTableros()
    public string Nombre { get; set; }
    public string Descripcion { get; set ; }

    public Tablero (CrearTableroViewModel tableroView)
    {
        IdUsuarioPropietario = tableroView.IdUsuarioPropietario; 
        Nombre = tableroView.Nombre;
        Descripcion = tableroView.Descripcion;
    }
    public Tablero (ModificarTableroViewModel tableroView)
    {
        Id = tableroView.Id;
        IdUsuarioPropietario = tableroView.IdUsuarioPropietario;
        Nombre = tableroView.Nombre;
        Descripcion = tableroView.Descripcion;
    }
    public Tablero(){}

    
}

ViewModels/TableroViewM/ModificarTableroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace tl2_tp10_2023_julian_quin.ViewModels;

public class ModificarTableroViewModel
{

  [Required(ErrorMessage = "Este campo es requerido")]
  [Display(Name = "Nombre")]
  public string Nombre { get; set; }

  [Required(ErrorMessage = "Este campo es requerido")]
  [Display(Name = "Descripcion")]
  public string Descripcion { get; set; }
  public int IdUsuarioPropietario { get; set; } 
  public int Id { get; set; }

  public ModificarTableroViewModel(Tablero tablero)
  {
    Id = tablero.Id;
    IdUsuarioPropietario = tablero.IdUsuarioPropietario;
    Nombre = tablero.Nombre;
    Descripcion = tablero.Descripcion;
  }
  public ModificarTableroViewModel() { }


}

ViewModels/TableroViewM/TableroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace tl2_tp10_2023_julian_quin.ViewModels;
public class TableroViewModel
{
    public int Id {get; set;} //lo necesito para los links(Editar o eliminar)
    public string Nombre { get ; set; }
    public string Descripcion { get ; set; }
    public string NombrePropietario {get;set;}

    public TableroViewModel(Tablero tablero)
    {
        Id = tablero.Id;
        Nombre = tablero.Nombre;
        Descripcion = tablero.Descripcion;
        NombrePropietario = tablero.NombrePropietario;
    }
    
}

Controllers/TableroController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_julian_quin.ViewModels;

namespace tl2_tp10_2023_julian_quin.Controllers;

public class TableroController : Controller
{
    private readonly ILogger<TableroController> _logger;
    private readonly ITableroRepository _accesoTableros;
    private readonly IUsuarioRepository _accesoUsuarios;

    public TableroController(ILogger<TableroController> logger, ITableroRepository tableroRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _accesoTableros = tableroRepository;
        _accesoUsuarios = usuarioRepository;
    }
    [HttpGet]
    public IActionResult Index()
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            var idUsuario =  IdSesion();
            var tablerosNoPropios = _accesoTableros.TablerosTareasUsuario(idUsuario);
            var tablerosPropios = _accesoTableros.TablerosDeUnUsuario(idUsuario);
            return View(new IndexTableroViewModel(tablerosPropios,tablerosNoPropios));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }
    [HttpGet]
    public IActionResult OtrosTableros(int idUsuario)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!EsAdmin()) return BadRequest();
            var tableros= _accesoTableros.TablerosRestantes(idUsuario);
            return View(new IndexTableroViewModel(tableros));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult NuevoTablero()
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var nuevoTablero = new CrearTableroViewModel();
            if (EsAdmin())
            {
                nuevoTablero.Usuarios = _accesoUsuarios.Usuarios();
                return View(nuevoTablero);
            }
            var idUsuario = (int)HttpContext.Session.GetInt32("Id");
            nuevoTablero.Usuarios.Add(_accesoUsuarios.UsuarioViaId(idUsuario));
            return View(nuevoTablero); 
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }

    [HttpPost]
    public IActionResult NuevoTablero(CrearTableroViewModel tablero)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index");
            var nuevotablero = new Tablero(tablero);
            _accesoTableros.NuevoTablero(nuevotablero);
            var tableros = _accesoTableros.Tableros();
            TempData["idTablero"] = tableros.FirstOrDefault(t => t.Nombre == tablero.Nombre).Id;
            TempData["Mensaje"] = "Nuevo";
            return RedirectToAction("Index");

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }

    [HttpGet]
    public IActionResult ModificarTablero(int idTablero)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var tablero = _accesoTableros.TableroViaId(idTablero);
            var idUsuario = IdSesion();
            var tableroAmodificadar = new ModificarTableroViewModel(tablero);
            return View(tableroAmodificadar);

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult ModificarTablero(ModificarTableroViewModel tablero)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index");
            var tableroModificaciones = new Tablero(tablero);
            _accesoTableros.ModificarTablero(tableroModificaciones, tableroModificaciones.Id);
            TempData["idTablero"] = tablero.Id;
            TempData["Mensaje"] = "Actualizado";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }
    public IActionResult EliminarTablero(int idTablero)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            if (!_accesoTableros.ExistenTareasEnTablero(idTablero))
            {
                _accesoTableros.EliminarTablero(idTablero);
                return RedirectToAction("Index");
            }
            return View("MensajeAdvertencia",idTablero); //id para ir al tablero
           
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }


    }
    private bool EsAdmin()
    {
        if (HttpContext.Session != null && HttpContext.Session.GetString("NivelAcceso") == "administrador") return true;
        return false;
    }

    private bool SeLogueo()
    {
        if (HttpContext.Session.GetString("Usuario") != null && HttpContext.Session.GetInt32("Id") != null
        && HttpContext.Session.GetString("NivelAcceso") != null) return true;
        return false;
    }
    private int IdSesion()
    {
        return (int)HttpContext.Session.GetInt32("Id");
    }


}

Controllers/TareaController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_julian_quin.ViewModels;

namespace tl2_tp10_2023_julian_quin.Controllers;

public class TareaController : Controller
{
    private readonly ILogger<TareaController> _logger;
    private readonly ITareasRepository _accesoTareas;
    private readonly ITableroRepository _accesoTableros;
    private readonly IUsuarioRepository _usuariosRepository;

    public TareaController(ILogger<TareaController> logger, ITareasRepository tareasRepository, ITableroRepository tableroRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _accesoTareas = tareasRepository;
        _accesoTableros = tableroRepository;
        _usuariosRepository = usuarioRepository;
    }

    [HttpGet]
    public IActionResult TareasTablerosPropios(int idTablero) //llega id de tableros propios
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            List<Tarea> tareas;
            tareas = _accesoTareas.TareasDeUnTablero(idTablero);
            return View(new IndexTareaViewModel(tareas));

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }

    [HttpGet]
    public IActionResult TareasTablerosNoPropios(int idTablero) //llega id de tableros no propios
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            List<Tarea> tareas;
            var idSession = IdSesion();
            tareas = _accesoTareas.TareasDeUnTablero(idTablero);
            ViewBag.idSession = idSession;
            var tareasView = new IndexTareaViewModel(tareas);
            return View(tareasView);

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }

    [HttpGet]
    public IActionResult NuevaTarea()//con opcion select de tableros
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var usuarioId = IdSesion();
            var nuevaTarea = new CrearTareaViewModel();
            nuevaTarea.Tableros = _accesoTableros.TablerosDeUnUsuario(usuarioId);
            nuevaTarea.Usuarios = _usuariosRepository.Usuarios();
            return View(nuevaTarea);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }

    [HttpGet]
    public IActionResult NuevaTareaDesdeUnTablero(int IdTablero) //sin opcion select de tableros
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var usuarioId = IdSesion();
            var nuevaTarea = new CrearTareaViewModel();
            nuevaTarea.Tableros = _accesoTableros.TablerosDeUnUsuario(usuarioId);
            nuevaTarea.Usuarios = _usuariosRepository.Usuarios();
            nuevaTarea.IdTablero = IdTablero;
            return View(nuevaTarea);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }


    [HttpPost]
    public IActionResult NuevaTarea(CrearTareaViewModel tarea)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index");
            var tareaConvertida = new Tarea(tarea);
            _accesoTareas.CrearTarea(tarea.IdTablero, tareaConvertida);
            var tareas = _accesoTareas.Tareas();
            TempData["idTarea"] = tareas.FirstOrDefault(t => t.Nombre == tarea.Nombre).Id;
            TempData["Mensaje"] = "Nueva";
            return RedirectToAction("TareasTablerosPropios", new { idTablero = tarea.IdTablero });

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult ModificarTarea(int idTarea)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var tarea = _accesoTareas.TareaId(idTarea);
            var tareaAmodificadar = new ModificarTareaViewModel(tarea);
            tareaAmodificadar.Usuarios = _usuariosRepository.Usuarios();
            return View(tareaAmodificadar);

        }
        catch (Exception ex)
        {
            _logger.LogError("Error al intentar modificar " + ex.ToString());
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult ModificarTarea(ModificarTareaViewModel tarea)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index");
            var tareaRecuperada = new Tarea(tarea);
            _accesoTareas.ModificarTarea(tarea.Id, tareaRecuperada);
            TempData["idTarea"] = tarea.Id;
            TempData["Mensaje"] = "Actualizada";
            return RedirectToAction("TareasTablerosPropios", new { idTablero = tarea.IdTablero });

        }
        catch (Exception ex)
        {
            _logger.LogError("Error al intentar modificar " + ex.ToString());
            return View("Error");
        }
    }

    public IActionResult EliminarTarea(int idTarea)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var tarea = _accesoTareas.TareaId(idTarea);
            var tablero = _accesoTableros.TableroViaId(tarea.IdTablero);
            _accesoTareas.EliminarTarea(idTarea);
            return RedirectToAction("TareasTablerosPropios", new { idTablero = tarea.IdTablero });

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Error");
        }

    }

    [HttpPost]
    public IActionResult CambiarEstadoTareaTablerosNoPropio (int idTarea, EstadoTarea estado) //desde la vista tareas-asignadas
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var tarea = _accesoTareas.TareaId(idTarea);
            tarea.Estado = estado;
            _accesoTareas.ModificarTarea(tarea.Id, tarea);
            TempData["EstadoTarea"] = "¡ Estado Actualizado !";
            return RedirectToAction("TareasTablerosNoPropios", new { idTablero = tarea.IdTablero });//(*)
        }
        catch (Exception Ex)
        {
            _logger.LogError(Ex.ToString());
            return View("Error");
        }
    }
    public IActionResult  CambiarEstadoTareaAsignadas(int idTarea, EstadoTarea estado) //desde la vista tareas-tableros-no-propios
    {
        try
        {
            
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Home", action = "Index" });
            var tarea = _accesoTareas.TareaId(idTarea);
            tarea.Estado = estado;
            _accesoTareas.ModificarTarea(tarea.Id, tarea);
            TempData["Mensaje"] = "Actualizada";
            TempData["idTarea"] = tarea.Id;
            return RedirectToAction("TareasAsignadas"); //la redireccion es diferente (*)
        }
        catch (Exception Ex)
        {
            _logger.LogError(Ex.ToString());
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult TareasAsignadas()
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            int usuarioId = IdSesion();
            var tareas = _accesoTareas.TareasDeUnUsuario(usuarioId);
            var tareasView = new IndexTareaViewModel(tareas);
            ViewBag.idSession = usuarioId;
            return View("TareasAsignadas", tareasView);

        }
        catch (Exception Ex)
        {
            _logger.LogError(Ex.ToString());
            return View("Error");
        }

    }
    [HttpPost]
    public IActionResult ListarTareaPorEstado(EstadoTarea estado)
    {
        try
        {
            if (!SeLogueo()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            int usuarioId = IdSesion();
            var tareas = _accesoTareas.TareasViaEstado(usuarioId, estado);
            var tareasVM = new IndexTareaViewModel(tareas);
            return View("TareasAsignadas", tareasVM);

        }
        catch (Exception Ex)
        {
            _logger.LogError(Ex.ToString());
            return View("Error");
        }

    }

    private int IdSesion()
    {
        return (int)HttpContext.Session.GetInt32("Id");
    }

    private bool EsAdmin()
    {
        if (HttpContext.Session != null && HttpContext.Session.GetString("NivelAcceso") == "administrador") return true;
        return false;
    }

    private bool SeLogueo()
    {
        if (HttpContext.Session.GetString("Usuario") != null && HttpContext.Session.GetInt32("Id") != null
        && HttpContext.Session.GetString("NivelAcceso") != null) return true;

        return false;
    }
}

Views/Tablero/MensajeAdvertencia.cshtml
@model int 
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning" role="alert">
                <h4 class="alert-heading">¡Acción No Permitida!</h4>
                <p>No puedes eliminar este tablero porque aún tiene tareas asociadas.</p>
                <hr>
                <p class="mb-0">Por favor, verifica las tareas antes de intentar eliminar el tablero.</p>
            </div>
        </div>
    </div>
</div>
<nav class="mb-4">
    <ul class="list-unstyled">
        <li class="d-inline-block">
            <a class="btn btn-secondary" role="button" aria-pressed="true" asp-controller="Tarea" asp-action="TareasTablerosPropios" asp-route-idTablero="@Model" style="color: rgb(255, 255, 255); background-color:rgb(0, 0, 0);">Ver el tablero</a>
        </li>
        <li class="d-inline-block">
            <a class="btn btn-secondary" role="button" aria-pressed="true" asp-controller="Tablero" asp-action="Index" style="color: rgb(255, 255, 255); background-color:rgb(0, 0, 0);">cancelar</a>
        </li>
    </ul>
</nav>

Views/Tablero/ModificarTablero.cshtml
@using tl2_tp10_2023_julian_quin.ViewModels
@model ModificarTableroViewModel
<h2>Modificar Tablero</h2>
<form class="forms_Modificar" asp-controller="Tablero" asp-action ="ModificarTablero"> 
    <input hidden asp-for="@Model.Id">
    <input hidden asp-for="@Model.IdUsuarioPropietario">
    <div class="form-group">
        <label asp-for="@Model.Nombre">Nombre</label>
        <input asp-for="@Model.Nombre" class="form-control" />
        <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Descripcion">Descripcion</label>
        <input asp-for="@Model.Descripcion" class="form-control" />
        <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success">Modificar</button>
</form>
@section Scripts { <partial name="_ValidationScriptsPartial" /> }

Views/Tablero/NuevoTablero.cshtml
@using tl2_tp10_2023_julian_quin.ViewModels
@model CrearTableroViewModel
<h2>Nuevo Tablero</h2>
<nav class="mb-4" style="margin-right: 10vw;">
    <ul class="list-unstyled" >
        <li class="d-inline-block"  style="margin-left: 340px;">
            <a class="btn btn-secondary" role="button" aria-pressed="true" asp-controller="Tablero" asp-action="Index" style="color: rgb(255, 255, 255); background-color:rgb(117, 117, 117);">Volver</a>
        </li>
    </ul>
</nav>
<form class="forms_Crear" asp-controller="Tablero" asp-action ="NuevoTablero"> 
    <div class="form-group">
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
        <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Descripcion"></label>
        <input asp-for="@Model.Descripcion" class="form-control"/>
        <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label asp-for="@Model.IdUsuarioPropietario"></label>
        <select asp-for="@Model.IdUsuarioPropietario" class="form-control">
            @foreach (var usuario in Model.Usuarios)
            {
                <option value="@usuario.Id">@usuario.NombreDeUsuario</option>
            }
        </select>
        <span asp-validation-for="@Model.IdUsuarioPropietario" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success">Crear</button>
</form>
@section Scripts { <partial name="_ValidationScriptsPartial" /> }

Views/Tablero/OtrosTableros.cshtml
@using tl2_tp10_2023_julian_quin.ViewModels
@model IndexTableroViewModel 
<div class="table-responsive">
        <table class="table" style="background-color: #77dd779c;">
            <thead style="background-color: #f3f3f3;">
                <tr>
                    <th>Nombre</th>
                    <th>Propietario</th>
                    <th>Descripción</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tablero in Model.TablerosPropios)
                {
                    <tr style="background-color: #83c3ff31; color: black;">
                        <td>@tablero.Nombre</td>
                        <td style="color: rgb(8, 37, 168);">@tablero.NombrePropietario</td>
                        <td>@tablero.Descripcion</td>
                        <td>
                            <a class="btn btn-sm" style="color: white;" role="button"
                                asp-controller="Tablero" asp-action="ModificarTablero"
                                asp-route-idTablero="@tablero.Id">
                               <img src="~/img/lapiz.png"alt="editar" style="width: 10mm; height: 10mm;">
                            </a>
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>
</div>

Views/Tablero/index.cshtml
@using tl2_tp10_2023_julian_quin.ViewModels
@model IndexTableroViewModel
@{ 
    var mensaje = TempData["Mensaje"] as string;
    int? idTablero = TempData["idTablero"] as int?;
}
<nav class="mb-4">
    <ul class="list-unstyled">
        <li class="d-inline-block mr-2">
            <a class="btn" style="background-color:  #636363c7; color: white;" role="button" aria-pressed="true"
                asp-controller="Tablero" asp-action="NuevoTablero">Nuevo Tablero</a>
        </li>
        <li class="d-inline-block">
            <a class="btn" style="background-color: #636363c7; color: white;" role="button" aria-pressed="true"
                asp-controller="Tarea" asp-action="NuevaTarea" asp-route-idTablero="">Crear Tareas</a>
        </li>
    </ul>
</nav>

<h4 class="text-center" class="mb-4">Tableros propios</h4>
@if (Model.TablerosPropios.Count() == 0)
{
    <p class="text-center"><strong>Aun no tienes ningún tablero</strong></p>
}
else
{      <div class="table-responsive">
        <table class="table">
            <tbody>
                @foreach (var tablero in Model.TablerosPropios)
                {
                    <tr>
                        <td hidden>@tablero.Id</td>
                        <td>@tablero.Nombre</td>
                        <td>@tablero.Descripcion</td>
                        <td>
                            <a class="btn btn-sm" style="color: rgb(0, 0, 0);" role="button"
                                asp-controller="Tablero" asp-action="ModificarTablero"
                                asp-route-idTablero="@tablero.Id">
                               <img src="~/img/lapiz.png"alt="editar" style="width: 10mm; height: 10mm;">Editar</a>

                            <a class="btn btn-sm" style="color: rgb(0, 0, 0);" role="button"
                                asp-controller="Tablero" asp-action="EliminarTablero" asp-route-idTablero="@tablero.Id"
                                onclick="return confirm('¿Estás seguro que quieres eliminar el elemento?')">
                                <img src="~/img/eliminar.png"alt="Eliminar" style="width: 10mm; height: 10mm;">Eliminar</a>

                            <a class="btn btn-sm" style="color: rgb(0, 0, 0);" role="button"
                                asp-controller="Tarea" asp-action="TareasTablerosPropios" asp-route-idTablero="@tablero.Id">
                                <img src="~/img/tareas.png"alt="tareas" style="width: 18mm; height: 10mm;">Tareas
                            </a>
                            <a class="btn btn-sm" style="color: rgb(0, 0, 0);" role="button"
                                asp-controller="Tarea" asp-action="NuevaTareaDesdeUnTablero" asp-route-idTablero="@tablero.Id">
                                <img src="~/img/nuevaTarea.png"alt="Nuevatarea" style="width: 12mm; height: 12mm;">Añadir Tarea
                            </a>
                            @if(mensaje!=null && idTablero == tablero.Id)
                            {
                                <p class="text-center" style="background-color : red; color: white; display: inline-block; padding: 3px; border-radius: 4px;">@mensaje</p>
                                mensaje = null;
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        </div>

}



<h4 class="text-center">Tableros donde tienes tareas</h4>
@if (Model.TablerosNoPropios.Count() == 0)
{
    <p class="text-center"> <strong>Aun no tienes tareas en ningun tablero<strong></p>
}
else
{
    <div class="table-responsive">
        <table class="table table-tb-no-propios">
            <tbody>
                @foreach (var tablero in Model.TablerosNoPropios)
                {
                    <tr>
                        <td hidden>@tablero.Id</td>
                        <td>@tablero.Nombre</td>
                        <td>@tablero.Descripcion</td>
                        <td>
                            <a class="btn btn-sm" style="color: rgb(0, 0, 0);" role="button"
                                asp-controller="Tarea" asp-action="TareasTablerosNoPropios" asp-route-idTablero="@tablero.Id">
                                <img src="~/img/tareas.png"alt="tareas" style="width: 18mm; height: 10mm;">Tareas
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}